### ISSUE TITLE
Home Page - Banner of each need to FIT based on the size of the screen

### ISSUE THREAD

**Issue by ratishnair** [adershsnair/eventapp#1]
The banner shows up as a small icture in the middle of the banner section..When user adds the banner for the first time, it is fitted to perfect screen size but after saving the event, it shrinks to small size. The picture (banner) of each event should be set to same size (stretched to alotted area of the event). At the event banner/Logo, please ,mention the right size of the picture that should be used for proper display of the banner to fit the screen.

**Comment by adershsnair** [comment]
Added the resolution to picture and adjusted the image size fixed.
