### ISSUE TITLE
The URL portion needs to show as a card and user should able to click and navigate to that website. (When we say card, for example, when you copy a URL on Facebook or Whatsapp, it changes the hyperlink URL to a card display. Similar kind of approach)

### ISSUE THREAD

**Issue by ratishnair** [adershsnair/eventapp#10]
The URL portion needs to show as a card and user should able to click and navigate to that website. (When we say card, for example, when you copy a URL on Facebook or Whatsapp, it changes the hyperlink URL to a card display. Similar kind of approach). Example attached

![url card example](https://cloud.githubusercontent.com/assets/20057979/16217200/2ba94cb2-373f-11e6-84e9-d7595281a825.png)

**Comment by adershsnair** [comment]
It is  not possible to get the full content i just added the title and url of the website
