### ISSUE TITLE
When keyboard gets active to comment or Type anything in profile, the caps lock must be on by default for first letter.

### ISSUE THREAD

**Issue by ratishnair** [adershsnair/eventapp#12]
When keyboard gets active to comment or Type anything in profile, the caps lock must be on by default for first letter.

**Comment by adershsnair** [comment]
Already solved.

**Comment by ratishnair** [comment]
Not fixed when user is creating an event and he is typing description or anything else. Please include the same fix on pages where ever the typing is expected by user.

**Comment by ratishnair** [comment]
![screenshot_2016-06-21-20-15-04](https://cloud.githubusercontent.com/assets/20057979/16250690/6082b802-37ed-11e6-8372-4649572bb40c.png)

**Comment by ratishnair** [comment]
As you can see in the screenshot, the capslock is not active when I selected that field.

**Comment by adershsnair** [comment]
Update the code from github and run.
