### ISSUE TITLE
Event Home page - thumbnail of photos taken or added from gallery by users need to be dispalyed with same size.

### ISSUE THREAD

**Issue by ratishnair** [adershsnair/eventapp#14]
Event Home page - thumbnail of photos taken or added from gallery by users need to be dispalyed with same size.

**Comment by adershsnair** [comment]
can you add an image for better understanding?

**Comment by ratishnair** [comment]
if you see in the screenshot. The first image is from gallery and it is bigger than the 2nd picture which was added by camera. Both needs to be same size
![screenshot_2016-06-21-20-29-47](https://cloud.githubusercontent.com/assets/20057979/16250869/0b9ce428-37ef-11e6-96db-6187cfd33205.png)

**Comment by ratishnair** [comment]
Issue is not resolved. Please see screenshot.

![screenshot_2016-06-22-08-55-22](https://cloud.githubusercontent.com/assets/20057979/16267318/2d4da6c6-3857-11e6-82af-70f276050b47.png)

**Comment by ratishnair** [comment]
Issue is still happening. Check git for screenshot
