### ISSUE TITLE
Application Home page - When user selects an event, the web browser opens with the URL in the event.

### ISSUE THREAD

**Issue by ratishnair** [adershsnair/eventapp#18]
When a user selects an event and if there is a URL included for that event, the user is navigated to that URL by just selecting the event from home page (Event list) of application.

For example, if an event has google URL in the URL section,
![screenshot_2016-06-25-12-38-52](https://cloud.githubusercontent.com/assets/20057979/16357917/50ba443e-3ad2-11e6-8eed-25d95a27e974.png)

And if user selects the event from Home page. Third one in the below screen

![screenshot_2016-06-25-12-38-29](https://cloud.githubusercontent.com/assets/20057979/16357921/5fa52040-3ad2-11e6-9696-bd4d27808ddb.png)

Instead of showing the Event page, its navigated to google website.

![screenshot_2016-06-25-12-38-44](https://cloud.githubusercontent.com/assets/20057979/16357928/7dd454c8-3ad2-11e6-93ca-d3a3baaf008a.png)

**Comment by adershsnair** [comment]
This is because of loading the url in web view for the card view of url. Some like google load as only popup.
