### ISSUE TITLE
Event Page - After a picture is added, the user cannot see it on the page

### ISSUE THREAD

**Issue by ratishnair** [adershsnair/eventapp#22]
After a picture is added, the user cannot see it on the page but if he presses in the area where the picture is suppose to be, the comment screen opens.

Below screen shows no picture even though user uploaded.
![screenshot_2016-06-25-13-18-58](https://cloud.githubusercontent.com/assets/20057979/16358105/cacd9e42-3ad7-11e6-9e45-2c3397a8f9f3.png)

When user presses in the area where the picture is supposed to display, the comment screens opens as seen below.
![screenshot_2016-06-25-13-19-03](https://cloud.githubusercontent.com/assets/20057979/16358104/cacd219c-3ad7-11e6-9ad4-0ae2f3a2d409.png)

User can enter comment but can't see the picture still.
![screenshot_2016-06-25-13-19-13](https://cloud.githubusercontent.com/assets/20057979/16358106/cace2dda-3ad7-11e6-82a6-98254783f9bc.png)

**Comment by adershsnair** [comment]
It is due to loading time so i just added an image to indicate loading.
