### ISSUE TITLE
Event Create Page - When a banner is selected, user is unable to reselect another pic if he wants to change it

### ISSUE THREAD

**Issue by ratishnair** [adershsnair/eventapp#3]
Event Create Page - When a banner is selected, user is unable to reselect another pic if he wants to change it

**Comment by adershsnair** [comment]
Already there please check
![screenshot_20160621-234224](https://cloud.githubusercontent.com/assets/7510991/16241152/08372e40-380a-11e6-9f2b-206b4b606980.png)
Please check

**Comment by ratishnair** [comment]
It works when user wants to change it while creating it. The issue is that if the owner of the event goes in an existing event, he cannot change it after already creating it.

**Comment by adershsnair** [comment]
Is it ok to add this in edit screen of event.

**Comment by ratishnair** [comment]
So you mean event owner will be able to edit event whenever they want to? If that is what you meant then, yes please add in the edit screen.

**Comment by adershsnair** [comment]
See menu button for our action options.
![screenshot_20160704-155609](https://cloud.githubusercontent.com/assets/7510991/16557865/d9c80732-41ff-11e6-89d1-dd1847851fa3.png)
![screenshot_20160704-155613](https://cloud.githubusercontent.com/assets/7510991/16557866/d9c97ba8-41ff-11e6-9678-c1760bb6942e.png)
